# Generated by Django 5.0 on 2023-12-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Categories_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categories_Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_M',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('P_Name', models.CharField(max_length=90)),
                ('P_Desc', models.TextField(blank=True, null=True)),
                ('P_Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Categories_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.categories')),
            ],
        ),
    ]
