# Generated by Django 5.0 on 2023-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0002_product_color_m_product_size_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_size',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
