# Generated by Django 5.0 on 2023-12-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0003_product_size_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_color',
            old_name='Color',
            new_name='color_m',
        ),
        migrations.RenameField(
            model_name='product_color',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_size',
            old_name='Color',
            new_name='product_color',
        ),
        migrations.RenameField(
            model_name='product_size',
            old_name='Size',
            new_name='size_m',
        ),
    ]
