# Generated by Django 5.0 on 2023-12-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0004_rename_color_product_color_color_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Img',
            fields=[
                ('Img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.URLField()),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.product_size')),
            ],
        ),
    ]
