# Generated by Django 5.0 on 2023-12-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0005_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_color',
            old_name='color_m',
            new_name='color',
        ),
    ]
