# Generated by Django 5.0 on 2023-12-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0006_rename_color_m_product_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_size',
            old_name='size_m',
            new_name='size',
        ),
    ]
