# Generated by Django 5.0 on 2023-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0007_rename_size_m_product_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product_img',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
