# Generated by Django 5.0 on 2023-12-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0008_remove_product_img_img_url_product_img_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='product_size',
        ),
        migrations.AddField(
            model_name='product_img',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ECom.product_color'),
        ),
    ]
